/*
 * Copyright 2026 FlowWarden
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.flowwarden.javers;

import org.bson.BsonDocument;
import org.javers.core.commit.CommitMetadata;
import org.javers.core.metamodel.object.CdoSnapshot;
import org.javers.core.metamodel.object.SnapshotType;

import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Provides access to Javers audit snapshot data and FlowWarden event metadata.
 *
 * <p>Instances are created by the FlowWarden Javers integration and passed to
 * handler methods annotated with {@link io.flowwarden.javers.annotation.OnInitial},
 * {@link io.flowwarden.javers.annotation.OnUpdate}, or
 * {@link io.flowwarden.javers.annotation.OnTerminal}.</p>
 *
 * @param <T> the entity type
 */
public interface JaversChangeContext<T> {

    // ---- Javers snapshot data ----

    /**
     * Returns the full Javers snapshot object.
     */
    CdoSnapshot getSnapshot();

    /**
     * Returns the snapshot type: {@code INITIAL}, {@code UPDATE}, or {@code TERMINAL}.
     */
    SnapshotType getSnapshotType();

    /**
     * Returns the Javers commit metadata (author, date, commit ID).
     */
    CommitMetadata getCommitMetadata();

    /**
     * Returns the list of properties that changed in this snapshot.
     * Empty for {@code INITIAL} snapshots.
     */
    List<String> getChangedProperties();

    /**
     * Returns the Javers snapshot version number.
     */
    long getVersion();

    /**
     * Returns the entity ID (the {@code cdoId} from the Javers global ID).
     */
    String getEntityId();

    // ---- FlowWarden event metadata (delegates) ----

    /** Unique event identifier generated by FlowWarden. */
    String getEventId();

    /** MongoDB cluster timestamp of the Change Stream event. */
    Instant getClusterTime();

    /** MongoDB resume token for this event. */
    BsonDocument getResumeToken();

    /** Immediately persists the current resume token checkpoint. */
    void saveCheckpointNow();

    /** Manually sends this event to the Dead Letter Queue. */
    void sendToDlq(String reason);

    /** Attaches custom metadata to this event. */
    void addMetadata(String key, Object value);

    /** Retrieves custom metadata by key. */
    <V> Optional<V> getMetadata(String key, Class<V> type);

    /** Returns all custom metadata (unmodifiable). */
    Map<String, Object> getAllMetadata();
}
